<<<<<<< HEAD
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5434:80"
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
=======
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports: 
      - 5432:5432
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: secret 
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
>>>>>>> d2742ffaea9aef1a8873990c8cee864ac7ea43f9

