FROM ubuntu:20.04

RUN mkdir -p /app
WORKDIR /app
RUN apt update && apt-get install -y git
RUN git clone https://github.com/psylopunk/pytonlib && cd pytonlib
COPY ./pytonlib/ton/distlib/linux/ /app/pytonlib/ton/distlib/linux/
COPY . /app
WORKDIR /app

RUN apt-get install -y git autoconf libtool && git clone https://github.com/wolfssl/wolfssl.git && cd wolfssl/ && \
./autogen.sh && ./configure --enable-sha512 && make && make install && ldconfig && cd /app
RUN sudo apt-get install -y python-dev python3-dev python-pip libffi-dev
RUN pip install wolfcrypt

RUN pip3 install -r requirements.txt  

CMD ["/bin/bash"]
